import { ROUTES } from "@/utils/constants";
import { getAuthUser } from "@/api/auth";
import NavWidget from "./NavWidget";
import "./styles.scss";
import PageHeader from "@/components/PageHeader";
import { Link } from "react-router-dom";

function DashboardPage() {
  const name = getAuthUser().data.name;

  return (
    <>
      <PageHeader selected={ROUTES.DASHBOARD} />

      <div className="dashboard-container">
        <div className="widget-container">
          <div style={{ alignSelf: "flex-start" }}>
            <h1>Welcome {name}</h1>
          </div>

          <div className="widget-row">
            <NavWidget>
              <p>Total Users Today</p>
              <h2>124 users</h2>
            </NavWidget>

            <NavWidget>
              <p>Total Time Spent Using</p>
              <h2>5 hours</h2>
            </NavWidget>

            <NavWidget>
              <p>Avg. Minutes Spent Using</p>
              <h2>7 minutes</h2>
            </NavWidget>
          </div>

          <div className="widget-row">
            <NavWidget>
              <div
                style={{
                  display: "flex",
                  flexDirection: "row",
                  padding: "20px 0px",
                }}
              >
                <div style={{ display: "flex", flexDirection: "column" }}>
                  <h2>Manage HDIL</h2>
                  <p style={{ textWrap: "wrap" }}>
                    Customize paintings being shown and edit annotations
                  </p>

                  <Link to={ROUTES.PAINTINGS}>
                    <button>Manage</button>
                  </Link>
                </div>
                <div>
                  <img src="https://loremflickr.com/180/180"></img>
                </div>
              </div>
            </NavWidget>

            <NavWidget>
              <div
                style={{
                  display: "flex",
                  flexDirection: "row",
                  gap: "12px",
                  padding: "20px 0px",
                }}
              >
                <div style={{ display: "flex", flexDirection: "column" }}>
                  <h2>Collected Data</h2>
                  <p style={{ textWrap: "wrap" }}>
                    Access and export data generated by the experience
                  </p>

                  <div>
                    <button>Export</button>
                  </div>
                </div>
                <div>
                  <img src="https://loremflickr.com/180/180"></img>
                </div>
              </div>
            </NavWidget>
          </div>
        </div>
      </div>
    </>
  );
}

export default DashboardPage;
