import { Link } from "react-router-dom";
import { useCallback, useMemo } from "react";
import { BsClock, BsPerson, BsStopwatch } from "react-icons/bs";
import { ROUTES } from "@/utils/constants";
import { getAuthUser } from "@/api/auth";
import NavWidget from "./NavWidget";
import "./styles.scss";
import PageHeader from "@/components/PageHeader";
import { getExport } from "@/api/export";
import heatmapImage from "@/assets/heatmap.png";
import paintingsImage from "@/assets/paintings.png";
import Footer from "@/components/Footer/Footer";
import { getViewerStats } from "@/api/viewers";

function DashboardPage() {
  const name = getAuthUser().data.name;

  const { data: viewerStats } = getViewerStats();
  const { viewersToday, totalTime, averageTime } = useMemo(() => {
    if (!viewerStats)
      return {
        viewersToday: "Loading...",
        totalTime: "Loading...",
        averageTime: "Loading...",
      };

    return {
      viewersToday: viewerStats.viewersToday + " users",
      totalTime: (viewerStats.totalTime / 3600).toFixed(1) + " hours",
      averageTime: (viewerStats.averageTime / 60).toFixed(1) + " minutes",
    };
  }, [viewerStats]);

  const { mutate: mutateGetExport, isPending } = getExport();

  const downloadExport = useCallback(async () => {
    mutateGetExport(undefined, {
      onSuccess: (blob) => {
        // fake a download button click
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "hdil_data.zip";
        document.body.appendChild(a);
        a.click();
        a.remove();
        window.URL.revokeObjectURL(url);
      },
      onError: (error) => {
        console.error("Download export failed:", error);
        alert("Failed to download export");
      },
    });
  }, [mutateGetExport]);

  return (
    <>
      <PageHeader selected={ROUTES.DASHBOARD} />

      <div className="dashboard-container">
        <div className="widget-container">
          <div style={{ alignSelf: "flex-start" }}>
            <h1>Welcome {name}</h1>
          </div>

          <div className="widget-row">
            <NavWidget>
              <p className="text-with-icon">
                <BsPerson className="icon" /> Total Users Today
              </p>
              <p className="big-text">{viewersToday}</p>
            </NavWidget>

            <NavWidget>
              <p className="text-with-icon">
                <BsClock className="icon" /> Total Time Spent Using
              </p>
              <p className="big-text">{totalTime}</p>
            </NavWidget>

            <NavWidget>
              <p className="text-with-icon">
                <BsStopwatch className="icon" /> Avg. Time Spent Using
              </p>
              <p className="big-text">{averageTime}</p>
            </NavWidget>
          </div>

          <div className="widget-row">
            <NavWidget>
              <div className="big-widget">
                <div style={{ display: "flex", flexDirection: "column" }}>
                  <h2>Manage HDIL</h2>
                  <p style={{ textWrap: "wrap" }}>
                    Customize paintings being shown and edit annotations
                  </p>

                  <Link to={ROUTES.PAINTINGS}>
                    <button>Manage</button>
                  </Link>
                </div>
                <div>
                  <img src={paintingsImage} />
                </div>
              </div>
            </NavWidget>

            <NavWidget>
              <div className="big-widget">
                <div style={{ display: "flex", flexDirection: "column" }}>
                  <h2>Collected Data</h2>
                  <p style={{ textWrap: "wrap" }}>
                    Access and export data generated by the experience
                  </p>

                  <div>
                    <button onClick={() => downloadExport()}>
                      {isPending ? "Loading..." : "Export"}
                    </button>
                  </div>
                </div>
                <div>
                  <img src={heatmapImage} />
                </div>
              </div>
            </NavWidget>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}

export default DashboardPage;
